force-app/main/default/objects/Case/fields/Address_State__c.field-meta.xml
<CustomField>
    <fullName>Address_State__c</fullName>
    <label>State</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Address_Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Address_Zipcode__c</fullName>
    <label>Zipcode</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case Connect</description>
    <label>Case Connect</label>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Intakes</relationshipLabel>
    <relationshipName>Intakes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Intake.recordType-meta.xml
<RecordType>
    <fullName>Intake</fullName>
    <active>true</active>
    <businessProcess>Intake</businessProcess>
    <label>Intake_</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Address_City__c.field-meta.xml
<CustomField>
    <fullName>Address_City__c</fullName>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Address_State__c.field-meta.xml
<CustomField>
    <fullName>Address_State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>IllinoisIndiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>MontanaNebraska</fullName>
            </value>
            <value>
                <fullName>Nevada</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
            <value>
                <fullName>New Mexico</fullName>
            </value>
            <value>
                <fullName>New York</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Address_ZipCode__c.field-meta.xml
<CustomField>
    <fullName>Address_ZipCode__c</fullName>
    <label>ZipCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Casevault_PID__c.field-meta.xml
<CustomField>
    <fullName>Casevault_PID__c</fullName>
    <label>Casevault PID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/County_Address__c.field-meta.xml
<CustomField>
    <fullName>County_Address__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Allegany</fullName>
                <default>true</default>
                <label>Allegany</label>
            </value>
            <value>
                <fullName>Anne Arundel</fullName>
            </value>
            <value>
                <fullName>Baltimore City</fullName>
            </value>
            <value>
                <fullName>Baltimore County</fullName>
            </value>
            <value>
                <fullName>Calvert</fullName>
            </value>
            <value>
                <fullName>Caroline</fullName>
            </value>
            <value>
                <fullName>Carroll</fullName>
            </value>
            <value>
                <fullName>Cecil</fullName>
            </value>
            <value>
                <fullName>Charles</fullName>
            </value>
            <value>
                <fullName>Dorchester</fullName>
            </value>
            <value>
                <fullName>Frederick</fullName>
            </value>
            <value>
                <fullName>Garrett</fullName>
            </value>
            <value>
                <fullName>Harford</fullName>
            </value>
            <value>
                <fullName>Howard</fullName>
            </value>
            <value>
                <fullName>Kent</fullName>
            </value>
            <value>
                <fullName>Montgomery</fullName>
            </value>
            <value>
                <fullName>Prince George&apos;s</fullName>
            </value>
            <value>
                <fullName>Queen Anne&apos;s</fullName>
            </value>
            <value>
                <fullName>Somerset</fullName>
            </value>
            <value>
                <fullName>St. Mary&apos;s</fullName>
            </value>
            <value>
                <fullName>Talbot</fullName>
            </value>
            <value>
                <fullName>Washington</fullName>
            </value>
            <value>
                <fullName>Wicomico</fullName>
            </value>
            <value>
                <fullName>Worcester</fullName>
            </value>
            <value>
                <fullName>Out of State</fullName>
            </value>
            <value>
                <fullName>OTHS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <inlineHelpText>It is a standard help text.
But cannot use next line, bold
Character limit around 500 character</inlineHelpText>
    <label>Date of Birth ⓕ</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Intake_Person_Role__c.field-meta.xml
<CustomField>
    <fullName>Intake_Person_Role__c</fullName>
    <label>Person Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Adoptive Parent</fullName>
            </value>
            <value>
                <fullName>Adult Biological Child</fullName>
            </value>
            <value>
                <fullName>Adult Child</fullName>
            </value>
            <value>
                <fullName>Advocate</fullName>
            </value>
            <value>
                <fullName>Alleged Maltreator</fullName>
            </value>
            <value>
                <fullName>Alleged Victim</fullName>
            </value>
            <value>
                <fullName>Biological Child</fullName>
            </value>
            <value>
                <fullName>Biological Parent</fullName>
            </value>
            <value>
                <fullName>Caregiver</fullName>
            </value>
            <value>
                <fullName>CASA Worker</fullName>
            </value>
            <value>
                <fullName>Casehead</fullName>
                <isActive>false</isActive>
                <label>Casehead</label>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Child Attorney</fullName>
            </value>
            <value>
                <fullName>Child Day Care Provider</fullName>
            </value>
            <value>
                <fullName>Conservator</fullName>
            </value>
            <value>
                <fullName>Court Therapist</fullName>
            </value>
            <value>
                <fullName>CPS Hist. Clrnc.- Requestor</fullName>
            </value>
            <value>
                <fullName>CPS Hist. Clrnc. - Subject</fullName>
            </value>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>Enhanced Aftercare Recipient</fullName>
            </value>
            <value>
                <fullName>Foster Parent</fullName>
            </value>
            <value>
                <fullName>Friend/Neighbor</fullName>
            </value>
            <value>
                <fullName>I &amp; R Participant</fullName>
            </value>
            <value>
                <fullName>Law Enforcement</fullName>
            </value>
            <value>
                <fullName>Legal Guardian</fullName>
            </value>
            <value>
                <fullName>Legal Representive</fullName>
            </value>
            <value>
                <fullName>Medical Professional</fullName>
            </value>
            <value>
                <fullName>Mental Health Professional</fullName>
            </value>
            <value>
                <fullName>Non-Victim Child</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SSN_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>SSN_Encrypted__c</fullName>
    <label>SSN</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Contact/fields/State_Id_Drivers_License__c.field-meta.xml
<CustomField>
    <fullName>State_Id_Drivers_License__c</fullName>
    <label>State Id/Drivers License</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investigation__c/Investigation__c.object-meta.xml
<CustomObject>
    <label>Investigation</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Investigation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Investigation__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Investigations</relationshipLabel>
    <relationshipName>Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investigation__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Connect</label>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Investigations</relationshipLabel>
    <relationshipName>Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Persons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipName>Persons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Persons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Case__c/Service_Case__c.object-meta.xml
<CustomObject>
    <label>Service Case</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Case ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Cases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Case__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Service Cases</relationshipLabel>
    <relationshipName>Service_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PersonSearchController.cls
public without sharing class PersonSearchController {
    
    @AuraEnabled
    public static String getContacts(String searchJSON, String recordId) {
        
        if(String.isNotBlank(searchJSON)) {
            
            List<Contact> contactList = new List<Contact> ();
            SearchInputWrapper inputWrap = (SearchInputWrapper) JSON.deserialize(searchJSON, SearchInputWrapper.class);
            Date personDOB = inputWrap.dob;
                        
            Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Persons Involved').getRecordTypeId();
            String contactJSON = 'SELECT Id, Name, FirstName, LastName, Address_Line_1__c, Address_Line_2__c, Address_City__c,Address_State__c,County_Address__c, Address_ZipCode__c, Casevault_PID__c,'+
                'SSN__c,Date_of_Birth__c, Gender__c, State_Id_Drivers_License__c,Intake_Person_Role__c, SSN_Encrypted__c  FROM Contact'; 
            contactJSON += ' WHERE LastName != null AND RecordTypeId = \'' + recordTypeId + '\'' ;
            
            if(String.isNotBlank(recordId)) {
                
                List<String> jnObjFields = new List<String>{'Id', 'Person__c'};
                String jnObjCondition = 'Intake__c = \'' + String.escapeSingleQuotes(recordId) + '\'' + ' OR ' + 
                						'Investigation__c = \'' + String.escapeSingleQuotes(recordId) + '\'' + ' OR ' + 
                						'Service_Case__c = \'' + String.escapeSingleQuotes(recordId) + '\'' + ' OR ' + 'Person__c = \'' + String.escapeSingleQuotes(recordId) + '\'';
            
        		List<Person__c> jnObjList = DataService.performQueryOperation(jnObjFields, 'Person__c', jnObjCondition, Utility.queryLimit);  
         		if(jnObjList.size() > 0) {
                    
                    String conIds='';
            		conIds +=' NOT IN (';
       				for(Person__c rec : jnObjList) {
                		conIds +='\''+String.escapeSingleQuotes(rec.Person__c)+'\',';
            		}
            		conIds = conIds.removeEnd(',');
            		conIds +=')';
                    contactJSON += ' AND Id  '+ conIds; 

         		}
                
            }
            
            if( String.isNotBlank(inputWrap.casevaultPid) ) {

                contactJSON +=  ' AND Casevault_PID__c = \'PE-'+ String.escapeSingleQuotes(inputWrap.casevaultPid) +'\'';
                
            } else {
                
                if( String.isNotBlank(inputWrap.firstName) ) {
				
                    String firstNameSoundexCode = Soundex_Algorithm.calculateSoundexCode(inputWrap.firstName);
                    if(String.isNotBlank(firstNameSoundexCode)) {
                        contactJSON += ' AND Firstname_soundex_keycode__c = \''+ String.escapeSingleQuotes(firstNameSoundexCode)+ '\'';
                    }
                }
                if( String.isNotBlank(inputWrap.lastName) ) {
                    
                    String lastNameSoundexCode = Soundex_Algorithm.calculateSoundexCode(inputWrap.lastName);
                    if(String.isNotBlank(lastNameSoundexCode)) {
                        contactJSON += ' AND Lastname_soundex_keycode__c = \''+ String.escapeSingleQuotes(lastNameSoundexCode)+ '\'';
                    } 
                }
                if( inputWrap.dob != NULL ) {
    
                    DateTime startDT = DateTime.newInstance(inputWrap.dob.addYears(-3).year(),inputWrap.dob.addYears(-3).month(),inputWrap.dob.addYears(-3).day());
                    DateTime endDT = DateTime.newInstance(inputWrap.dob.addYears(3).year(),inputWrap.dob.addYears(3).month(),inputWrap.dob.addYears(3).day());
                    contactJSON +=  ' AND Date_of_Birth__c >= ' + startDT.format('yyyy-MM-dd') + ' AND Date_of_Birth__c <= ' +  endDT.format('yyyy-MM-dd');
                }
                if( String.isNotBlank(inputWrap.ssn) ) {
                
                    contactJSON +=  ' AND SSN__c = \''+ String.escapeSingleQuotes(inputWrap.ssn) +'\'';
            	}
                if( String.isNotBlank(inputWrap.dlNo) ) {
    
                    contactJSON +=  ' AND State_Id_Drivers_License__c = \''+ String.escapeSingleQuotes(inputWrap.dlNo) +'\'';
                }
                if( String.isNotBlank(inputWrap.addressLine1) ) {
    
                    contactJSON +=  ' AND Address_Line_1__c LIKE \'%'+ String.escapeSingleQuotes(inputWrap.addressLine1) +'%\'';
                }
                if( String.isNotBlank(inputWrap.addressLine2) ) {
    
                    contactJSON +=  ' AND Address_Line_2__c LIKE \'%'+ String.escapeSingleQuotes(inputWrap.addressLine2) +'%\'';
                }
                if( String.isNotBlank(inputWrap.state) ) {
                
                    contactJSON +=  ' AND Address_State__c = \''+ String.escapeSingleQuotes(inputWrap.state) +'\'';
            	}
                if( String.isNotBlank(inputWrap.city) ) {
                
                    contactJSON +=  ' AND Address_City__c = \''+ String.escapeSingleQuotes(inputWrap.city) +'\'';
            	}
                if( String.isNotBlank(inputWrap.county) ) {
                
                    contactJSON +=  ' AND County_Address__c = \''+ String.escapeSingleQuotes(inputWrap.county) +'\'';
            	}
                if( String.isNotBlank(inputWrap.zipcode) ) {
                
                    contactJSON +=  ' AND Address_ZipCode__c = \''+ String.escapeSingleQuotes(inputWrap.zipcode) +'\'';
            	}
            } 
            contactJSON +=' ORDER BY Date_of_Birth__c ASC  LIMIT 500';
            System.debug('Query:::'+contactJSON);
            contactList = Database.query(contactJSON);            
            return JSON.serialize(contactList);
            
        } else {
            return null;
        }
    }

    @AuraEnabled
    public static String personsIntakeInvSC(String selectedPersonJSON) {
       
        if(String.isNotBlank(selectedPersonJSON)) {

            Contact selectedPerson = (Contact)JSON.deserialize(selectedPersonJSON, Contact.class);
            List <Person__c> jnObjRec = [SELECT Id, Intake__c, Investigation__c, Person__c, Service_Case__c FROM Person__c WHERE Person__c = :selectedPerson.Id];
            Set<Id> intakeSet = new Set<Id> ();
            Set<Id> investigationSet = new Set<Id> ();
            Set<Id> serviceSet = new Set<Id> ();
            for(Person__c personRec : jnObjRec){
                if(String.isNotBlank(personRec.Intake__c))
                    intakeSet.add(personRec.Intake__c);
                else if(String.isNotBlank(personRec.Investigation__c))
                    investigationSet.add(personRec.Investigation__c);
                else if(String.isNotBlank(personRec.Service_Case__c))
                    serviceSet.add(personRec.Service_Case__c);
            }
            PersonsWrapper wrapperIns = new PersonsWrapper();
            if(intakeSet.size()>0) {
                
                wrapperIns.intake = [SELECT Id, CaseNumber, Origin, Jurisdiction__c FROM Case WHERE Id IN :intakeSet]; 
            }
            if(investigationSet.size()>0) {
                
                wrapperIns.investigation = [SELECT Id, Name, CPS_Response_Type__c FROM Investigation__c WHERE Id IN :investigationSet];
            }
           if(serviceSet.size()>0) {
                
                wrapperIns.serviceCase = [SELECT Id, Name, Status__c, Number_of_days__c FROM Service_Case__c WHERE Id IN :serviceSet];
            }
            return JSON.serialize(wrapperIns);
        } else {
            return null;
        }
    }
    
    /*public static String findDuplicateRecord(String firstName, String lastName) {

        String inQuery = '';
        Contact contactIns = new Contact();

        if(String.isNotBlank(firstName)) {
            contactIns.FirstName = firstName;
        }
        if(String.isNotBlank(lastName)) {
            contactIns.LastName = lastName;
        }

        List<Datacloud.FindDuplicatesResult> results = Datacloud.FindDuplicates.findDuplicates(new List<Contact>{contactIns});
        if(results.size() > 0) {

            for (Datacloud.DuplicateResult dr : results[0].getDuplicateResults()) { 

                if (dr.matchResults.size() > 0 && dr.getMatchResults()[0].matchRecords.size() > 0 && dr.getMatchResults()[0].getMatchRecords()[0].getRecord() != null) { 
                
                    Contact duplicateContact = (Contact) dr.getMatchResults()[0].getMatchRecords()[0].getRecord();
                    inQuery += '\''+ String.escapeSingleQuotes(duplicateContact.Id) +'\'' +' ,';
                }            
            } 
            inQuery =  inQuery.removeEnd(' ,');
        }
        return inQuery;
    }*/

    @AuraEnabled
    public static String getPicklistValues() {

        PicklistWrapper picklistWrapIns = new PicklistWrapper();
        picklistWrapIns.statePicklist = Utility.getPicklistinfo('Contact', 'Address_State__c', false);
        picklistWrapIns.countyPicklist = Utility.getPicklistinfo('Contact', 'County_Address__c', false);
        return JSON.serialize(picklistWrapIns);
    }

    public class PicklistWrapper {

        @AuraEnabled
        public List<Utility.pickListWrap> statePicklist;
        @AuraEnabled
        public List<Utility.pickListWrap> countyPicklist;
    }
    
    public class SearchInputWrapper {
        
        public String firstName; 
        public String lastName;
        public Date dob;
        public String ssn;
        public String casevaultPid;
        public String dlNo; 
        public String addressLine1; 
        public String addressLine2;
        public String city;
        public String state;
        public String county;
        public String zipcode;
    }

    public class PersonsWrapper {

        public List<Case> intake;
        public List<Investigation__c> investigation;
        public List<Service_Case__c> serviceCase;
        
        public PersonsWrapper() {
            
        }
    }
    
}