force-app/main/default/objects/Case/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case Connect</description>
    <label>Case Connect</label>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Intakes</relationshipLabel>
    <relationshipName>Intakes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investigation__c/Investigation__c.object-meta.xml
<CustomObject>
    <label>Investigation</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Investigation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Investigation__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Connect</label>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Investigations</relationshipLabel>
    <relationshipName>Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investigation__c/fields/Supervisor_Approver__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Investigations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Notes__c/fields/Contact_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Contact_Purpose__c</fullName>
    <label>Contact Purpose</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advocacy</fullName>
            </value>
            <value>
                <fullName>Affidavit of Disclosure</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Case Closure</fullName>
            </value>
            <value>
                <fullName>Case Consultation</fullName>
            </value>
            <value>
                <fullName>Case Management</fullName>
            </value>
            <value>
                <fullName>Case Monitoring</fullName>
            </value>
            <value>
                <fullName>Case Plan/Review</fullName>
            </value>
            <value>
                <fullName>Case Staffing</fullName>
            </value>
            <value>
                <fullName>Case Transfers</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Corrective Action Plan</fullName>
            </value>
            <value>
                <fullName>Court</fullName>
            </value>
            <value>
                <fullName>CPS</fullName>
            </value>
            <value>
                <fullName>Crisis Intervention</fullName>
            </value>
            <value>
                <fullName>Database/Internet search</fullName>
            </value>
            <value>
                <fullName>Day Care Assessment</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Evaluation</fullName>
            </value>
            <value>
                <fullName>Family Assessment</fullName>
            </value>
            <value>
                <fullName>Family Team Meeting</fullName>
            </value>
            <value>
                <fullName>FIM-After Removal</fullName>
            </value>
            <value>
                <fullName>FIM-Case transfers</fullName>
            </value>
            <value>
                <fullName>FIM-Disruption</fullName>
            </value>
            <value>
                <fullName>FIM-Emergency Placement change</fullName>
            </value>
            <value>
                <fullName>FIM-Permanency changes</fullName>
            </value>
            <value>
                <fullName>FIM-Planned Placement Change</fullName>
            </value>
            <value>
                <fullName>FIM-Planned Removal/ Considered removal</fullName>
            </value>
            <value>
                <fullName>FIM-Prior to Removal/Considered removal</fullName>
            </value>
            <value>
                <fullName>FIM-Visitation Plan</fullName>
            </value>
            <value>
                <fullName>Worker Visit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipName>Persons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Persons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipName>Persons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person_Involved__c/Person_Involved__c.object-meta.xml
<CustomObject>
    <label>Person Involved</label>
    <nameField>
        <displayFormat>PI-{000}</displayFormat>
        <label>Person Involved Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons Involved</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person_Involved__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Persons Involved</relationshipLabel>
    <relationshipName>Persons_Involved</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person_Involved__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notes</label>
    <referenceTo>Notes__c</referenceTo>
    <relationshipLabel>Persons Involved</relationshipLabel>
    <relationshipName>Persons_Involved</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person_Involved__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Persons Involved</relationshipLabel>
    <relationshipName>Persons_Involved</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Area</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Area</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Program_Area__c.field-meta.xml
<CustomField>
    <fullName>Program_Area__c</fullName>
    <label>Program Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CPS-IR</fullName>
            </value>
            <value>
                <fullName>CPS-AR</fullName>
            </value>
            <value>
                <fullName>In Home</fullName>
            </value>
            <value>
                <fullName>GAP</fullName>
            </value>
            <value>
                <fullName>Adoption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Case__c/Service_Case__c.object-meta.xml
<CustomObject>
    <label>Service Case</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Case ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Cases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Case__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <defaultValue>&quot;In Progress&quot;</defaultValue>
    <label>Status</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InHomeChecklistController.cls
public with sharing class InHomeChecklistController {
    
    @AuraEnabled
    Public static String getChildRecords(String recordId, String objectApiName) {
        
        WrapperClass initWrap = new WrapperClass();
        DateTime createdDate;
        if(objectApiName == 'Service_Case__c') {
            
            initWrap.serviceCaseRecord = [SELECT Id, CreatedDate
                                     	  FROM Service_Case__c
                                      	  WHERE Id = :recordId];
            initWrap.initialDate = initWrap.serviceCaseRecord.CreatedDate+7;
        	initWrap.riskAssessmentInitialDueDate = initWrap.serviceCaseRecord.CreatedDate+30;
            createdDate = initWrap.serviceCaseRecord.CreatedDate;
        } else if(objectApiName == 'Investigation__c') {
            
            initWrap.investigationRecord = [SELECT Id, CreatedDate
                                     	  FROM Investigation__c
                                      	  WHERE Id = :recordId];
            initWrap.initialDate = initWrap.investigationRecord.CreatedDate+7;
        	initWrap.riskAssessmentInitialDueDate = initWrap.investigationRecord.CreatedDate+30;
            createdDate = initWrap.investigationRecord.CreatedDate;
        }
        
        initWrap.todayDate = DateTime.now();
        

        Set<Id> personIds = new Set<Id>();
        
        for(Program_Assignment__c assignmentIns : [SELECT Id, Program_Area__c, Contact__c FROM Program_Assignment__c WHERE (Service_Case__c = :recordId OR Investigation__c =:recordId)
                                                   AND (Program_Area__c = 'In Home' OR Program_Area__c = 'Out of Home') ORDER BY Program_Area__c ASC]) 
            {
                if(assignmentIns.Program_Area__c == 'In Home') {
                    personIds.add(assignmentIns.Contact__c);
                } else if(assignmentIns.Program_Area__c == 'Out of Home' && personIds.contains(assignmentIns.Contact__c)) {
                    personIds.remove(assignmentIns.Contact__c);
                }
            }

        Notes__c notesRecord = getNotesDetails(recordId, personIds, initWrap.initialDate, createdDate);
        if(notesRecord != null) {
            
            initWrap.notesRecord = notesRecord;
            initWrap.workerName = notesRecord.CreatedBy.Name;
            initWrap.completedDate = notesRecord.CreatedDate;
        } else {
            
            initWrap.notesRecord = new Notes__c();
            initWrap.workerName = null;
            initWrap.completedDate = null;
        }
        
        Assessment__c safecRecord = getSAFECDetails(recordId, personIds);
        
        if(safecRecord !=null) {
            
            initWrap.safecAssessmentRecord = safecRecord;
        } else {
            
            initWrap.safecAssessmentRecord = new Assessment__c();
        }
        
        Assessment__c riskRecord = getRiskAssessmentDetails(recordId, personIds);
        
        if(riskRecord !=null) {
            
            initWrap.riskAssessmentRecord = riskRecord;
        } else {
            
            initWrap.riskAssessmentRecord = new Assessment__c();
        }
        
        return JSON.serialize(initWrap);
        
    }
    
    
    Public static Notes__c getNotesDetails(String recordId, Set<Id> personIds,DateTime initialdate,DateTime createddate) {
        
        Map<Id, Notes__c> notesMap = new Map<Id, Notes__c>([SELECT Id, Contact_Type__c, CreatedBy.Name, Contact_Date__c, CreatedDate 
                                    FROM Notes__c  
                                    WHERE Contact_Purpose__c INCLUDES('Worker Visit','Case Management','Family Assessment') 
                                    AND (Contact_Type__c = 'Face to Face' 
                                         OR Contact_Type__c = 'Initial Face to Face')
                                    AND Contact_was_initiated_received__c = 'Initiated'
                                    AND Contact_was_Attempted_Completed__c  = 'Completed'
                                    AND (Service_Case__c = :recordId OR Investigation__c =:recordId)
                                    AND (Contact_Date__c >= :Date.valueOf(createddate))
                                    AND (Contact_Date__c <= :Date.valueOf(initialdate)) ORDER BY CreatedDate DESC]);
        
       
        Set<Id> personsInvolved = new Set<Id>();
        Set<Id> personsNotInvolved = new Set<Id>();
        List<Person_Involved__c> getPersonsInvolved = [SELECT Id, Notes__c, Person__c FROM Person_Involved__c WHERE Notes__c IN:notesMap.keySet()];
          system.debug('dd '+getPersonsInvolved);
        for(Person_Involved__c involvedRec : getPersonsInvolved) {
            personsInvolved.add(involvedRec.Person__c);
        }
        for(Id recId : personIds) {
            if(!personsInvolved.contains(recId)) {
                personsNotInvolved.add(recId);
            } 
        }
        if(personsNotInvolved.isEmpty() && notesMap.size()>0) {
            system.debug('res '+notesMap.values());
            return notesMap.values()[0];
        } else {
            return null;
        }
        
        
    }
    
    Public static Assessment__c getSAFECDetails(String recordId, Set<Id> personIds) {
        
        Map<Id, Assessment__c> safecMap = new Map<Id, Assessment__c>([SELECT Id, Assessment_Type__c, Case_Worker_Name__c, Supervisor_Name__c,CreatedBy.Name,CreatedDate,
                                            Safety_Assessment_Approval_Date_Time__c, Supervisor_Approver__r.Name,
                                            Workers_Name__c,Submitted_Date__c 
                                            FROM Assessment__c  
                                            WHERE Assessment_Type__c ='SAFE-C'
                                            AND (Service_Case__c = :recordId OR Investigation__c =:recordId)
                                            AND Approval_Status__c ='Approved']);
        
        
        Set<Id> personsInvolved = new Set<Id>();
        Set<Id> personsNotInvolved = new Set<Id>();
        List<Person_Involved__c> getPersonsInvolved = [SELECT Id, Assessment__c, Person__c FROM Person_Involved__c WHERE Assessment__c IN:safecMap.keySet()];
        for(Person_Involved__c involvedRec : getPersonsInvolved) {
            personsInvolved.add(involvedRec.Person__c);
        }
        
        for(Id recId : personIds) {
            if(!personsInvolved.contains(recId)) {
                personsNotInvolved.add(recId);
            } 
        }
        if(personsNotInvolved.isEmpty() && safecMap.size() > 0) {
            return safecMap.values()[0];
        } else {
            return null;
        }
        
        
    }
    
    Public static Assessment__c getRiskAssessmentDetails(String recordId, Set<Id> personIds) {
        
        Map<Id, Assessment__c> riskAssessmentMap = new Map<Id, Assessment__c>([SELECT Id, Assessment_Type__c, Case_Worker_Name__c, Supervisor_Name__c,CreatedBy.Name,CreatedDate,
                                                     Safety_Assessment_Approval_Date_Time__c, Supervisor_Approver__r.Name,
                                                     Workers_Name__c,Submitted_Date__c 
                                                     FROM Assessment__c  
                                                     WHERE (Assessment_Type__c ='Family risk Reassessment' OR Assessment_Type__c ='Family Initial Risk Assessment')
                                                     AND (Service_Case__c = :recordId OR Investigation__c =:recordId) 
                                                     AND Approval_Status__c ='Approved']);
        

		Set<Id> personsInvolved = new Set<Id>();
        Set<Id> personsNotInvolved = new Set<Id>();
        List<Person_Involved__c> getPersonsInvolved = [SELECT Id, Assessment__c, Person__c FROM Person_Involved__c WHERE Assessment__c IN:riskAssessmentMap.keySet()];
         for(Person_Involved__c involvedRec : getPersonsInvolved) {
            personsInvolved.add(involvedRec.Person__c);
        }
        
        for(Id recId : personIds) {
            if(!personsInvolved.contains(recId)) {
                personsNotInvolved.add(recId);
            } 
        }
        if(personsNotInvolved.isEmpty() && riskAssessmentMap.size() > 0) {
            return riskAssessmentMap.values()[0];
        } else {
            return null;
        }        
        
    }
    
    public class WrapperClass { 
        
        @AuraEnabled
        public List<Person__c> personRecords;
        @AuraEnabled
        public Service_Case__c  serviceCaseRecord;
        @AuraEnabled
        public Investigation__c investigationRecord;
        @AuraEnabled
        public datetime  initialDate;
        @AuraEnabled
        public datetime  riskAssessmentInitialDueDate;
        @AuraEnabled
        public datetime  todayDate;
        @AuraEnabled
        public String workerName;
        @AuraEnabled
        public datetime completedDate;
        @AuraEnabled
        public Assessment__c safecAssessmentRecord;
        @AuraEnabled
        public Assessment__c riskAssessmentRecord;
        @AuraEnabled
        public Notes__c notesRecord;
    }
    
}