force-app/main/default/objects/Case/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Case Connect</description>
    <label>Case Connect</label>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Intakes</relationshipLabel>
    <relationshipName>Intakes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF( NOT( ISBLANK(  Date_of_Birth__c  ) ) &amp;&amp;   ISBLANK( Date_of_Death__c ) ,
  IF( DATE( 2000 , MONTH( Date_of_Birth__c ) , DAY( Date_of_Birth__c) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
     YEAR (Today()) - YEAR ( Date_of_Birth__c ),
     YEAR (Today()) - YEAR ( Date_of_Birth__c ) -1 ),
  IF(NOT( ISBLANK(  Date_of_Birth__c  ) ) &amp;&amp;   NOT(ISBLANK( Date_of_Death__c )),IF( DATE( 2000 , MONTH( Date_of_Birth__c ) , DAY( Date_of_Birth__c) ) &lt;= DATE( 2000 , MONTH( Date_of_Death__c ) , DAY( Date_of_Death__c ) ),
     YEAR (Date_of_Death__c) - YEAR ( Date_of_Birth__c ),
     YEAR (Date_of_Death__c) - YEAR ( Date_of_Birth__c ) -1 ),null) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Casevault_PID__c.field-meta.xml
<CustomField>
    <fullName>Casevault_PID__c</fullName>
    <label>Casevault PID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <inlineHelpText>It is a standard help text.
But cannot use next line, bold
Character limit around 500 character</inlineHelpText>
    <label>Date of Birth ⓕ</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Person_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Person_Image_URL__c</fullName>
    <defaultValue>&quot;https://casevault-dev-ed--c.vf.force.com/resource/1665391669000/unknownpersonImg&quot;</defaultValue>
    <label>Person Image URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Investigation__c/Investigation__c.object-meta.xml
<CustomObject>
    <label>Investigation</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Investigation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Investigation__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Investigations</relationshipLabel>
    <relationshipName>Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investigation__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Connect</label>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Investigations</relationshipLabel>
    <relationshipName>Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Persons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipName>Persons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Is_Caregiver__c.field-meta.xml
<CustomField>
    <fullName>Is_Caregiver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Caregiver ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Persons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipName>Persons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Area</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Area</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <label>Relationship</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Is_Caregiver__c.field-meta.xml
<CustomField>
    <fullName>Is_Caregiver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Caregiver?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationships (Person)</relationshipLabel>
    <relationshipName>Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Person_Related_To__c.field-meta.xml
<CustomField>
    <fullName>Person_Related_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person Related To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationships (Person Related To)</relationshipLabel>
    <relationshipName>Relationships2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Relationship_Values__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Values__c</fullName>
    <label>Relationship Values</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brother - Adoptive</fullName>
            </value>
            <value>
                <fullName>Brother - Biological</fullName>
            </value>
            <value>
                <fullName>Brother - Half</fullName>
            </value>
            <value>
                <fullName>Brother - Step</fullName>
            </value>
            <value>
                <fullName>Child care provider/worker</fullName>
            </value>
            <value>
                <fullName>Child - Adoptive</fullName>
            </value>
            <value>
                <fullName>Child - Biological</fullName>
            </value>
            <value>
                <fullName>Child - Custodial/Guardianship</fullName>
            </value>
            <value>
                <fullName>Child - Foster</fullName>
            </value>
            <value>
                <fullName>Child - Putative</fullName>
            </value>
            <value>
                <fullName>Child - Step</fullName>
            </value>
            <value>
                <fullName>Co-Worker</fullName>
            </value>
            <value>
                <fullName>Daycare Child</fullName>
            </value>
            <value>
                <fullName>Father - Adoptive</fullName>
            </value>
            <value>
                <fullName>Father - Biological</fullName>
            </value>
            <value>
                <fullName>Father - Foster</fullName>
            </value>
            <value>
                <fullName>Father - Putative</fullName>
            </value>
            <value>
                <fullName>Father - Step</fullName>
            </value>
            <value>
                <fullName>Foster - Parent</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Godchild</fullName>
            </value>
            <value>
                <fullName>Godparent</fullName>
            </value>
            <value>
                <fullName>Custodial/Guardianship</fullName>
            </value>
            <value>
                <fullName>In-law</fullName>
            </value>
            <value>
                <fullName>Maternal Aunt</fullName>
            </value>
            <value>
                <fullName>Maternal Cousin</fullName>
            </value>
            <value>
                <fullName>Maternal Grandchild</fullName>
            </value>
            <value>
                <fullName>Maternal Grandparent</fullName>
            </value>
            <value>
                <fullName>Maternal Great Aunt/Uncle</fullName>
            </value>
            <value>
                <fullName>Maternal Great Grandchild</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Service Case is closed</errorMessage>
        <filterItems>
            <field>Service_Case__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Close</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Case__c/Service_Case__c.object-meta.xml
<CustomObject>
    <label>Service Case</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Case ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Cases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Case__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Service Cases</relationshipLabel>
    <relationshipName>Service_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GenogramRelationshipController.cls
public class GenogramRelationshipController {
    
    @AuraEnabled
    public static String getAllPersons(String recordId) {
        
        getInitialWrapper initWrap = new getInitialWrapper ();
        Id personInvolvedRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Persons Involved').getRecordTypeId();
        
        initWrap.relationshipPicklist = Utility.getPicklistinfo('Relationship__c','Relationship_Values__c',false);
        FieldLevelSecurity.checkFieldAccessByCriteria('Name, Age__c,Gender__c,Date_of_Birth__c, Casevault_PID__c', 'view', 'Contact',  Boolean.valueOf(Label.HasNamespace));
        List<String> jnObjFields = new List<String>{'Id', 'Person__c','Is_Caregiver__c'};
            String jnObjCondition = 'Person__r.RecordTypeId = \''+ String.escapeSingleQuotes(personInvolvedRecordTypeId)+ '\''+'AND (Intake__c = \'' + String.escapeSingleQuotes(recordId) + '\'' + ' OR ' + 
            'Investigation__c = \'' + String.escapeSingleQuotes(recordId) + '\'' + ' OR ' + 
            'Service_Case__c = \'' + String.escapeSingleQuotes(recordId) + '\'' + ' OR ' + 'Person__c = \'' + String.escapeSingleQuotes(recordId) + '\')';
        List<Person__c> jnObjList = DataService.performQueryOperation(jnObjFields, 'Person__c', jnObjCondition, Utility.queryLimit);        
        initWrap.jnObjectRecords = (List<Person__c>)jnObjList;
        
        String contactCondition = '';
        
        
        String conIds='';
        if(jnObjList.size() > 0) {
            conIds +=' IN (';
            
            for(Person__c rec : jnObjList) {
                conIds +='\''+String.escapeSingleQuotes(rec.Person__c)+'\',';
            }
            conIds = conIds.removeEnd(',');
            conIds +=')';
            
        }
        else{
            conIds +=' IN('+'\''+'\')';
        }
        contactCondition += ' Id  '+ conIds;     
        
        
        
        List<String> contactFields = new List<String>{'Id','Name', 'Age__c','Gender__c','Date_of_Birth__c', 'Casevault_PID__c','Person_Image_URL__c','Date_of_Death__c'};
            /* String contactCondition = 'Service_Case__c = \'' + String.escapeSingleQuotes(recordId) + '\'' + ' OR ' + 
'Intake__c = \'' + String.escapeSingleQuotes(recordId) + '\'' + ' OR ' + 'Investigation__c = \'' + String.escapeSingleQuotes(recordId) + '\'';*/
            List<SObject> sObjListcontact = DataService.performQueryOperation(contactFields, 'Contact', contactCondition, Utility.queryLimit);        
        if(sObjListcontact.size() > 0) {
            initWrap.contactList = (List<Contact>) sObjListcontact;
        }
        
        List<String> relationFields = new List<String>{'Person__c', 'Person_Related_To__c', 'Person_Related_To__r.Name', 'Relationship_Values__c', 'Is_Caregiver__c'};
            String relationCondition = ' Person__c '+conIds;
        
        List<SObject> sObjListrelation = DataService.performQueryOperation(relationFields, 'Relationship__c', relationCondition, Utility.queryLimit);
        initWrap.allRelationshipRecords = (List<Relationship__c>)sObjListrelation;
        
        Set<Id> personIds = new Set<Id>();
        for(Person__c rec : initWrap.jnObjectRecords) {
            personIds.add(rec.Person__c);
        }
        
        
        initWrap.programAssignmentRecords = [SELECT Id, Name, Contact__c 
                                             FROM Program_Assignment__c
                                             WHERE Contact__c IN: personIds
                                             AND End_Date__c =NULL
                                             AND (Service_Case__c =:recordId OR Investigation__c =: recordId)];
        
        initWrap.collateralRecords = [SELECT Id, Collateral_Full_Name__c 
                                      FROM Collateral__c 
                                      WHERE (Service_Case__c =:recordId OR Investigation__c =: recordId)];
        return JSON.serialize(initWrap);
    }
    
    @AuraEnabled
    public static String getRelationRecord(String personId, String recordId, List<String> personIds) {
        
        if(String.isNotBlank(personId)) {
            
            getRelationshipWrapper initWrap = new getRelationshipWrapper ();
            
            initWrap.relationshipRecords = [SELECT Id, Person__c, Person_Related_To__c, Person_Related_To__r.Name ,Relationship_Values__c,
                                            Person_Related_To__r.Person_Image_URL__c
                                            FROM Relationship__c
                                            WHERE Person__c =:personId
                                            AND (Service_Case__c =:recordId OR Investigation__c =: recordId OR Victim__c =: recordId)];
            initWrap.otherRelationshipRecords = [SELECT Id, Person__c, Person_Related_To__c, Person_Related_To__r.Name ,
                                                 Relationship_Values__c, Service_Case__c, Service_Case__r.Name, Investigation__c,
                                                 Investigation__r.Name,Person_Related_To__r.Person_Image_URL__c, Victim__c, Victim__r.CaseNumber 
                                            	 FROM Relationship__c
                                           		 WHERE Person__c =:personId 
                                                 AND Person_Related_To__c NOT IN :personIds
                                           		 AND (Service_Case__c !=:recordId OR Investigation__c !=: recordId OR Victim__c !=: recordId)
                                                 AND (Service_Case__c != NULL OR Investigation__c != NULL OR Victim__c != NULL)];
           Set<Id> otherPersonId = new Set<Id>();
           for(Relationship__c rec: initWrap.otherRelationshipRecords) {
                otherPersonId.add(rec.Person_Related_To__c);
           }
           initWrap.childRemovalRecords = [SELECT Id, Child__c, Removal_End_Date_Time__c, Service_Case__c 
                                           FROM Child_Removal__c
                                           WHERE (Service_Case__c =:recordId OR Investigation__c =: recordId)
                                           OR Child__c IN :otherPersonId];
            return JSON.serialize(initWrap);
        } else {
            return null;
        }
    }
    
    @AuraEnabled
    public static String saveRelationship(String relationshipJSON, String recordId) {
        
        if (String.isNotBlank(relationshipJSON)) {
            
            Relationship__c relationship = (Relationship__c)JSON.deserialize(relationshipJSON,Relationship__c.class);
                        
            if (String.isBlank(relationship.Id)) {
                FieldLevelSecurity.checkFieldAccessByCriteria('Person__c, Person_Related_To__c, Relationship_Values__c, Is_Caregiver__c', 'create', 'Relationship__c',  Boolean.valueOf(Label.HasNamespace));
                insert relationship;
            } else {
                FieldLevelSecurity.checkFieldAccessByCriteria('Person__c, Person_Related_To__c, Relationship_Values__c, Is_Caregiver__c', 'update', 'Relationship__c',  Boolean.valueOf(Label.HasNamespace));
                update relationship;
            }
            return relationship.Id;
        } else {
            return null;
        }
        
    }
    
    
    public class getInitialWrapper { 
        
        @AuraEnabled
        public List<Utility.pickListWrap> relationshipPicklist;
        @AuraEnabled
        public List<Contact> contactList;
        @AuraEnabled
        public List<Person__c> jnObjectRecords;
        @AuraEnabled
        public List<Relationship__c> allRelationshipRecords;
        @AuraEnabled
        public List<Program_Assignment__c> programAssignmentRecords;
        @AuraEnabled
        public List<Collateral__c> collateralRecords;
        
    }
    Public class getRelationshipWrapper {
        @AuraEnabled
        public List<Relationship__c> relationshipRecords;
        @AuraEnabled
        public List<Relationship__c> otherRelationshipRecords;
        @AuraEnabled
        public List<Program_Assignment__c> programAssignmentRecords;
        @AuraEnabled
        public List<Child_Removal__c > childRemovalRecords;
        
    }
    
}