force-app/main/default/objects/Assessment__c/fields/Case_Worker_Signature__c.field-meta.xml
<CustomField>
    <fullName>Case_Worker_Signature__c</fullName>
    <label>Case Worker Signature</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/Caseworker_Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Caseworker_Signature_Date__c</fullName>
    <label>Caseworker Signature Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Assessment_Safety_Plan__c/fields/Responsible_Partie__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Partie__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible Parties</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Assessment Safety Plans</relationshipLabel>
    <relationshipName>Assessment_Safety_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person_Involved__c/Person_Involved__c.object-meta.xml
<CustomObject>
    <label>Person Involved</label>
    <nameField>
        <displayFormat>PI-{000}</displayFormat>
        <label>Person Involved Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons Involved</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person_Involved__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Persons Involved</relationshipLabel>
    <relationshipName>Persons_Involved</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person_Involved__c/fields/Is_Caregiver__c.field-meta.xml
<CustomField>
    <fullName>Is_Caregiver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Caregiver</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Person_Involved__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Persons Involved</relationshipLabel>
    <relationshipName>Persons_Involved</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person_Involved__c/fields/Signature__c.field-meta.xml
<CustomField>
    <fullName>Signature__c</fullName>
    <label>Signature</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Person_Involved__c/fields/Signature_Date__c.field-meta.xml
<CustomField>
    <fullName>Signature_Date__c</fullName>
    <label>Signature Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/safetyPlanPdfController.cls
public class safetyPlanPdfController {
    
    public string assessmentId{get; set;}
    public Assessment__c assessmentRecord {get; set;}
    public list<Assessment_Safety_Plan__c> safetyPlanList {get; set;}
    public list<Person_Involved__c > personList {get; set;}
    
    Public  safetyPlanPdfController(){
        
        assessmentId  = ApexPages.CurrentPage().getparameters().get('id');
        safetyPlanList = new List<Assessment_Safety_Plan__c>();
        
        assessmentRecord = [SELECT Id, Name, CreatedBy.Name, Supervisor_Approver__r.Name ,
                            Case_Worker_Signature__c, Caseworker_Signature_Date__c ,
                            SAFEC_Date_Time_Assessment_Initiated__c 
                            FROM Assessment__c 
                            WHERE Id =:assessmentId];
        
        String removeImageTag;
        if(assessmentRecord.Case_Worker_Signature__c != NULL) {
        removeImageTag = assessmentRecord.Case_Worker_Signature__c.replaceAll('&amp;','&');
        assessmentRecord.Case_Worker_Signature__c = removeImageTag.substring(10,removeImageTag.length()-8);
        }
        safetyPlanList = [SELECT Id, Question_Name__c, Specific_Danger_Influence__c, 
                          Action_Required__c, Date_to_be_Completed__c, Responsible_Partie__r.Name,
                          Re_evaluation_Date__c  
                          FROM Assessment_Safety_Plan__c 
                          WHERE Assessment__c =: assessmentId];
        
        List<Person_Involved__c> linkRecords = [SELECT Id, Person__r.Name, Signature__c ,Signature_Date__c 
                                                FROM Person_Involved__c 
                                                WHERE Assessment__c =:assessmentId 
                                                AND Is_Caregiver__c =true];
        
        personList = new List<Person_Involved__c>();
        for(Person_Involved__c link : linkRecords) {
            if(link.Signature__c != NULL) {
                String removeTag = link.Signature__c.replaceAll('&amp;','&');
                link.Signature__c = removeTag.substring(10,removeTag.length()-8);
                personList.add(link);
            }
            
        }
        
    }
    
    
}