force-app/main/default/objects/Payment_Summary__c/Payment_Summary__c.object-meta.xml
<CustomObject>
    <label>Payment Summary</label>
    <nameField>
        <label>Payment Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Summary__c/fields/Child__c.field-meta.xml
<CustomField>
    <fullName>Child__c</fullName>
    <formula>Person__r.FirstName+&apos; &apos;+Person__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Child</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Summary__c/fields/Payment_Generated__c.field-meta.xml
<CustomField>
    <fullName>Payment_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Summary__c/fields/Per_Diem_Rate__c.field-meta.xml
<CustomField>
    <fullName>Per_Diem_Rate__c</fullName>
    <label>Per Diem Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Summary__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payment Summary</relationshipLabel>
    <relationshipName>Payment_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Summary__c/fields/Placement__c.field-meta.xml
<CustomField>
    <fullName>Placement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Placement</label>
    <referenceTo>Placement__c</referenceTo>
    <relationshipLabel>Payment Summary</relationshipLabel>
    <relationshipName>Payment_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Summary__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Summary</relationshipLabel>
    <relationshipName>Payment_Summary</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Summary__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Summary</fullName>
            </value>
            <value>
                <fullName>Receivable Summary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Persons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Placement__c/Placement__c.object-meta.xml
<CustomObject>
    <label>Placement</label>
    <nameField>
        <displayFormat>PL-{0000}</displayFormat>
        <label>Placement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Placements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Placement__c/fields/Begin_Date__c.field-meta.xml
<CustomField>
    <fullName>Begin_Date__c</fullName>
    <label>Begin Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Child__c.field-meta.xml
<CustomField>
    <fullName>Child__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child</label>
    <lookupFilter>
        <active>false</active>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Placement_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Placement_Approval_Status__c</fullName>
    <label>Placement Approval Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Placement_Living_Arrangement_Type__c.field-meta.xml
<CustomField>
    <fullName>Placement_Living_Arrangement_Type__c</fullName>
    <label>Placement/Living Arrangement Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Placement</fullName>
            </value>
            <value>
                <fullName>Living Arrangement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Placement_Structure__c.field-meta.xml
<CustomField>
    <fullName>Placement_Structure__c</fullName>
    <label>Placement Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular Foster Care</fullName>
            </value>
            <value>
                <fullName>Guardianship Assistance Program</fullName>
            </value>
            <value>
                <fullName>Emergency Shelter (Agency)</fullName>
            </value>
            <value>
                <fullName>Independent Living Residential Program</fullName>
            </value>
            <value>
                <fullName>Formal Kinship Care</fullName>
            </value>
            <value>
                <fullName>Restricted (Relative) Foster Care</fullName>
            </value>
            <value>
                <fullName>Intermediate Foster Care</fullName>
            </value>
            <value>
                <fullName>Treatment Foster Care</fullName>
            </value>
            <value>
                <fullName>Emergency Foster Home Care</fullName>
            </value>
            <value>
                <fullName>Residential Group Homes</fullName>
            </value>
            <value>
                <fullName>Emergency Group Shelter Care</fullName>
            </value>
            <value>
                <fullName>Emergency Foster Care Retainer</fullName>
            </value>
            <value>
                <fullName>After care room and board</fullName>
            </value>
            <value>
                <fullName>Alternative Living Units</fullName>
            </value>
            <value>
                <fullName>Teen Mother Programs</fullName>
            </value>
            <value>
                <fullName>Residential Treatment Centers</fullName>
            </value>
            <value>
                <fullName>Refugee Child</fullName>
            </value>
            <value>
                <fullName>Therapeutic Group Homes</fullName>
            </value>
            <value>
                <fullName>Adoptive Home</fullName>
            </value>
            <value>
                <fullName>Pre-Finalized Adoptive Home</fullName>
            </value>
            <value>
                <fullName>Treatment Foster Care Level 1</fullName>
            </value>
            <value>
                <fullName>Treatment Foster Care Level 2</fullName>
            </value>
            <value>
                <fullName>Treatment Foster Care Level 3</fullName>
            </value>
            <value>
                <fullName>Treatment Foster Care Level 4</fullName>
            </value>
            <value>
                <fullName>Intermediate Foster Care Difficulty of Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Placement__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Provider</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Placements</relationshipLabel>
    <relationshipName>Placements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Public_Provider_Rate__mdt/Public_Provider_Rate__mdt.object-meta.xml
<CustomObject>
    <label>Public Provider Rate</label>
    <pluralLabel>Public Provider Rates</pluralLabel>
</CustomObject>

force-app/main/default/objects/Public_Provider_Rate__mdt/fields/Estimated_Rate_Value__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Rate_Value__c</fullName>
    <label>Estimated Rate Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Public_Provider_Rate__mdt/fields/Placement_Structure__c.field-meta.xml
<CustomField>
    <fullName>Placement_Structure__c</fullName>
    <label>Placement Structure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular Foster Care</fullName>
                <default>true</default>
                <label>Regular Foster Care</label>
            </value>
            <value>
                <fullName>Guardianship Assistance Program</fullName>
            </value>
            <value>
                <fullName>Emergency Shelter (Agency)</fullName>
            </value>
            <value>
                <fullName>Independent Living Residential Program</fullName>
            </value>
            <value>
                <fullName>Formal Kinship Care</fullName>
            </value>
            <value>
                <fullName>Restricted (Relative) Foster Care</fullName>
            </value>
            <value>
                <fullName>Intermediate Foster Care</fullName>
            </value>
            <value>
                <fullName>Treatment Foster Care</fullName>
            </value>
            <value>
                <fullName>Emergency Foster Home Care</fullName>
            </value>
            <value>
                <fullName>Residential Group Homes</fullName>
            </value>
            <value>
                <fullName>Emergency Group Shelter Care</fullName>
            </value>
            <value>
                <fullName>Emergency Foster Care Retainer</fullName>
            </value>
            <value>
                <fullName>After care room and board</fullName>
            </value>
            <value>
                <fullName>Alternative Living Units</fullName>
            </value>
            <value>
                <fullName>Teen Mother Programs</fullName>
            </value>
            <value>
                <fullName>Residential Treatment Centers</fullName>
            </value>
            <value>
                <fullName>Refugee Child</fullName>
            </value>
            <value>
                <fullName>Therapeutic Group Homes</fullName>
            </value>
            <value>
                <fullName>Adoptive Home</fullName>
            </value>
            <value>
                <fullName>Pre-Finalized Adoptive Home</fullName>
            </value>
            <value>
                <fullName>Treatment Foster Care Level 1</fullName>
            </value>
            <value>
                <fullName>Treatment Foster Care Level 2</fullName>
            </value>
            <value>
                <fullName>Treatment Foster Care Level 3</fullName>
            </value>
            <value>
                <fullName>Treatment Foster Care Level 4</fullName>
            </value>
            <value>
                <fullName>Intermediate Foster Care Difficulty of Care</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentGenerationDailyRuns.cls
public class PaymentGenerationDailyRuns implements Schedulable {
    
     public static Map<String,Decimal> publicProviderRateMap;
     public static List<Payment_Summary__c > paymentSummaryList;
     public static List<Public_Provider_Rate__mdt> publicProviderRate;
     public static Map<Id,Placement__c> placementMap;
     public void execute(SchedulableContext sc) {
        
        generatePayment();
    }
    
    public static void generatePayment() {
        
        publicProviderRate = new List<Public_Provider_Rate__mdt>();
        publicProviderRate = [SELECT Id, Estimated_Rate_Value__c, Placement_Structure__c 
                                                              FROM Public_Provider_Rate__mdt];
        
        //Iterate public provider and put in map placementstructure,ratevalue;
        publicProviderRateMap = new Map<String,Decimal>();
        paymentSummaryList = new  List<Payment_Summary__c>();
        for(Public_Provider_Rate__mdt publicRate : publicProviderRate) {
            
            publicProviderRateMap.put(publicRate.Placement_Structure__c,publicRate.Estimated_Rate_Value__c);
        }
        
        //initialization of beginDateChangedRecord list;
        List<Placement__History> beginDateChangedRecord = new List<Placement__History>();
        //initialization of endDateChangedRecord list;
        List<Placement__History> endDateChangedRecord = new List<Placement__History>();
        //initialization of placementIds set;
        Set<Id> placementIds = new Set<Id>();
        //Query placementHistoryRecords;
        List<Placement__History> placementHistoryRecord =  [SELECT Id, ParentId, OldValue, NewValue, Field 
                                                            FROM Placement__History 
                                                            WHERE CreatedDate = TODAY]; 
        
        //Iterate placement History Record to separate begin date or end date changed record;
        for(Placement__History ph : placementHistoryRecord) {
            
            //Check for begin date changed;
            if(ph.OldValue != NULL && ph.Field == 'Begin_Date__c') {
                
                beginDateChangedRecord.add(ph);
                placementIds.add(ph.ParentId);
            
            //Check for end date changed;
            } else if(ph.OldValue != NULL && ph.Field == 'End_Date__c') {
                
                endDateChangedRecord.add(ph);
                placementIds.add(ph.ParentId);
            }
        }
            
        Date monthStartDate = System.today().toStartOfMonth();
        //Query placement record and put in map Id,Placement
        placementMap = new Map<Id,Placement__c>([SELECT Id, Provider__r.RecordType.DeveloperName, Placement_Approval_Status__c, 
                                                                      Child__c, Placement_Structure__c, Provider__c
                                                                      FROM Placement__c 
                                                                      WHERE Id IN:placementIds 
                                                                      AND Begin_Date__c < :monthStartDate 
                                                                      AND (End_Date__c < :monthStartDate OR End_Date__c=NULL)
                                                                      AND Placement_Living_Arrangement_Type__c ='Placement'
                                                                      ORDER BY CreatedDate DESC]);

        //initialization paymentRec object
        Payment_Summary__c paymentRec = new Payment_Summary__c();
        
        //Iterate beginDateChangedRecord
        for(Placement__History beginDateRec : beginDateChangedRecord){
            
            paymentRec = new Payment_Summary__c();
            
            //Check for Begin date added;
            if(DATE.valueOf(beginDateRec.OldValue) > DATE.valueOf(beginDateRec.NewValue)) {
                
                Date startDate = DATE.valueOf(beginDateRec.NewValue);
                Date endDate = DATE.valueOf(beginDateRec.OldValue);
                createPayments(startDate, endDate, beginDateRec, 'Payment Summary');
                
            } else if(DATE.valueOf(beginDateRec.OldValue) < DATE.valueOf(beginDateRec.NewValue)) {
                
                Date startDate = DATE.valueOf(beginDateRec.OldValue);
                Date endDate = DATE.valueOf(beginDateRec.NewValue);
                createPayments(startDate, endDate, beginDateRec, 'Receivable Summary');
            }
                
                
        }
        
        for(Placement__History endDateRec : endDateChangedRecord){
            
            paymentRec = new Payment_Summary__c();
            //Check for Begin date added;
            if (DATE.valueOf(endDateRec.OldValue) < DATE.valueOf(endDateRec.NewValue)) {
                
                Date startDate = DATE.valueOf(endDateRec.OldValue);
                Date endDate = DATE.valueOf(endDateRec.NewValue);
                createPayments(startDate, endDate, endDateRec, 'Payment Summary');
          
            } else if(DATE.valueOf(endDateRec.OldValue) > DATE.valueOf(endDateRec.NewValue)) {
                
                Date startDate = DATE.valueOf(endDateRec.NewValue);
                Date endDate = DATE.valueOf(endDateRec.OldValue);
                createPayments(startDate, endDate, endDateRec, 'Receivable Summary');
                
            }
        }
        
        if(paymentSummaryList.size() > 0) {
            
            insert paymentSummaryList;
        }
        
        
    }
    
    public static void createPayments(Date startDate, Date endDate, Placement__History historyRecord, String paymentType) {
        
        Integer totalMonths = startDate.monthsBetween(endDate)+1;
        Payment_Summary__c paymentRec = new Payment_Summary__c();
        
        if(startDate.monthsBetween(endDate) !=0) {
                    
                    for(Integer i=0; i<totalMonths; i++) {
                        paymentRec = new Payment_Summary__c();
                       
                        if(i == 0) {
                           
                            paymentRec.Start_Date__c = startDate;
                            paymentRec.End_Date__c = (Date.newInstance(startDate.year(), startDate.month() , 1).addMonths(1)) - 1;
                            
                        } else if(i == totalMonths-1) {
                             
                            paymentRec.Start_Date__c = endDate.toStartOfMonth();
                            paymentRec.End_Date__c = endDate;
                            
                        } else {
                            
                            paymentRec.End_Date__c = (Date.newInstance(startDate.year(), startDate.month() , 1).addMonths(i+1)) - 1;
                    		paymentRec.Start_Date__c = (startDate.addMonths(i)).toStartOfMonth();
                           
                    		
                        }
                        
                            paymentRec.Person__c = placementMap.get(historyRecord.ParentId).Child__c;
                    		paymentRec.Provider__c = placementMap.get(historyRecord.ParentId).Provider__c;
                    		paymentRec.Payment_Generated__c = true;
                        	paymentRec.Type__c = paymentType;
                    		paymentRec.Service_Type__c = placementMap.get(historyRecord.ParentId).Placement_Structure__c;
                    		paymentRec.Per_Diem_Rate__c = publicProviderRateMap.get(paymentRec.Service_Type__c);
                    		paymentSummaryList.add(paymentRec);
                        
                    }
                    
                  
                } else {
                    
                    paymentRec.Start_Date__c = startDate;
                    paymentRec.End_Date__c = endDate;
                    paymentRec.Person__c = placementMap.get(historyRecord.ParentId).Child__c;
                    paymentRec.Provider__c = placementMap.get(historyRecord.ParentId).Provider__c;
                    paymentRec.Payment_Generated__c = true;
                    paymentRec.Type__c = paymentType;
                    paymentRec.Service_Type__c = placementMap.get(historyRecord.ParentId).Placement_Structure__c;
                    paymentRec.Per_Diem_Rate__c = publicProviderRateMap.get(paymentRec.Service_Type__c);
                    paymentSummaryList.add(paymentRec);
                    
                } 
        
    }
    
}