force-app/main/default/objects/Collateral__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>APGRB Attorney</fullName>
                <isActive>false</isActive>
                <label>APGRB Attorney</label>
            </value>
            <value>
                <fullName>Attorney</fullName>
                <isActive>false</isActive>
                <label>Attorney</label>
            </value>
            <value>
                <fullName>Attorney Adult</fullName>
            </value>
            <value>
                <fullName>Attorney Child</fullName>
            </value>
            <value>
                <fullName>Attorney General</fullName>
                <isActive>false</isActive>
                <label>Attorney General</label>
            </value>
            <value>
                <fullName>Attorney Other</fullName>
            </value>
            <value>
                <fullName>Caretaker/Caregiver</fullName>
            </value>
            <value>
                <fullName>Caretaker-Caregiver</fullName>
                <isActive>false</isActive>
                <label>Caretaker-Caregiver</label>
            </value>
            <value>
                <fullName>Child Advocate - CASA</fullName>
            </value>
            <value>
                <fullName>Child Welfare Staff</fullName>
            </value>
            <value>
                <fullName>Clergy</fullName>
            </value>
            <value>
                <fullName>Client Attorney</fullName>
                <isActive>false</isActive>
                <label>Client Attorney</label>
            </value>
            <value>
                <fullName>Counselor/Therapist</fullName>
            </value>
            <value>
                <fullName>Counselor-Therapist</fullName>
                <isActive>false</isActive>
                <label>Counselor-Therapist</label>
            </value>
            <value>
                <fullName>Day Care Staff</fullName>
            </value>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>Detention Center</fullName>
                <isActive>false</isActive>
                <label>Detention Center</label>
            </value>
            <value>
                <fullName>Detention Center Staff</fullName>
            </value>
            <value>
                <fullName>Doctor</fullName>
                <isActive>false</isActive>
                <label>Doctor</label>
            </value>
            <value>
                <fullName>Emergency Shelter</fullName>
                <isActive>false</isActive>
                <label>Emergency Shelter</label>
            </value>
            <value>
                <fullName>Ex-Spouse</fullName>
                <isActive>false</isActive>
                <label>Ex-Spouse</label>
            </value>
            <value>
                <fullName>FIM-Assigned Caseworker/Supervisor</fullName>
                <isActive>false</isActive>
                <label>FIM-Assigned Caseworker/Supervisor</label>
            </value>
            <value>
                <fullName>FIM-Facilitator</fullName>
                <isActive>false</isActive>
                <label>FIM-Facilitator</label>
            </value>
            <value>
                <fullName>FIM-Non-assigned casewoker/supervisor</fullName>
                <isActive>false</isActive>
                <label>FIM-Non-assigned casewoker/supervisor</label>
            </value>
            <value>
                <fullName>Foster Parent</fullName>
                <isActive>false</isActive>
                <label>Foster Parent</label>
            </value>
            <value>
                <fullName>Foster Sibling</fullName>
                <isActive>false</isActive>
                <label>Foster Sibling</label>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Godparent</fullName>
                <isActive>false</isActive>
                <label>Godparent</label>
            </value>
            <value>
                <fullName>Government Agency</fullName>
                <isActive>false</isActive>
                <label>Government Agency</label>
            </value>
            <value>
                <fullName>Grandfather</fullName>
                <isActive>false</isActive>
                <label>Grandfather</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <inlineHelpText>It is a standard help text.
But cannot use next line, bold
Character limit around 500 character</inlineHelpText>
    <label>Date of Birth ⓕ</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Investigation__c/Investigation__c.object-meta.xml
<CustomObject>
    <label>Investigation</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Investigation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Investigation__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Investigations</relationshipLabel>
    <relationshipName>Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investigation__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Connect</label>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Investigations</relationshipLabel>
    <relationshipName>Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Persons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipName>Persons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Persons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipName>Persons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Area</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Area</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/Relationship__c.object-meta.xml
<CustomObject>
    <label>Relationship</label>
    <nameField>
        <label>Relationship</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relationship__c/fields/Collateral__c.field-meta.xml
<CustomField>
    <fullName>Collateral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collateral</label>
    <referenceTo>Collateral__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationships (Person)</relationshipLabel>
    <relationshipName>Relationships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attorney Adult</fullName>
            </value>
            <value>
                <fullName>Attorney Child</fullName>
            </value>
            <value>
                <fullName>Attorney Other</fullName>
            </value>
            <value>
                <fullName>Caretaker/Caregiver</fullName>
            </value>
            <value>
                <fullName>Child Advocate - CASA</fullName>
            </value>
            <value>
                <fullName>Child Welfare Staff</fullName>
            </value>
            <value>
                <fullName>Clergy</fullName>
            </value>
            <value>
                <fullName>Counselor/Therapist</fullName>
            </value>
            <value>
                <fullName>Day Care Staff</fullName>
            </value>
            <value>
                <fullName>Decision Maker</fullName>
            </value>
            <value>
                <fullName>Detention Center Staff</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>Guardian – Ad litem</fullName>
            </value>
            <value>
                <fullName>Hospital Staff</fullName>
            </value>
            <value>
                <fullName>Living Arrangement Contact</fullName>
            </value>
            <value>
                <fullName>Medical Consultant</fullName>
            </value>
            <value>
                <fullName>Medical Professional</fullName>
            </value>
            <value>
                <fullName>Neighbor</fullName>
            </value>
            <value>
                <fullName>Parent Surrogate</fullName>
            </value>
            <value>
                <fullName>Parole Officer</fullName>
            </value>
            <value>
                <fullName>Probation Officer</fullName>
            </value>
            <value>
                <fullName>Relative</fullName>
            </value>
            <value>
                <fullName>School Staff</fullName>
            </value>
            <value>
                <fullName>Truancy Officer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Service Case is closed</errorMessage>
        <filterItems>
            <field>Service_Case__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Close</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Case__c/Service_Case__c.object-meta.xml
<CustomObject>
    <label>Service Case</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Case ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Cases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Case__c/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake ID</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Service Cases</relationshipLabel>
    <relationshipName>Service_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CollateralController.cls
public with sharing class CollateralController {
    
    @AuraEnabled
    public static string getCollaterals(Id recordId){
        
        List<Collateral__c> collaterals = [SELECT Name, First_Name__c, Middle_Name__c, Last_Name__c 
                                           FROM Collateral__c 
                                           WHERE Service_Case__c = :recordId 
                                           ORDER BY LastModifiedDate DESC];
        return JSON.serialize(collaterals);
    }
    
    @AuraEnabled
    public static string getCollateral(Id collateralId, String objectName){
        
        CollateralWrapper initWrap = new CollateralWrapper();
        String parentId;
        
        if(String.isNotBlank(collateralId) && objectName == 'Collateral__c') {
            
            
            initWrap.collateral = [SELECT Name, Date_of_Birth__c , End_Date__c , Start_Date__c, Service_Case__c,
                                   Investigation__c , Intake__c 
                                   FROM Collateral__c 
                                   WHERE Id =:collateralId];
            
            initWrap.relationshipRecords = [SELECT Id, Person__c, Role__c , Relationship_Values__c 
                                            FROM Relationship__c
                                            WHERE Collateral__c =:collateralId];
            
            if(String.isNotBlank(initWrap.collateral.Service_Case__c)) {
                
                parentId = initWrap.collateral.Service_Case__c;
                
            } else if(String.isNotBlank(initWrap.collateral.Investigation__c)){
                
                parentId = initWrap.collateral.Investigation__c;
                
            } else if(String.isNotBlank(initWrap.collateral.Intake__c)){
                
                parentId = initWrap.collateral.Intake__c;
                
            }
            
        } else {
            
            parentId = collateralId;       
            
        }
        
        Set<Id> personIds = new Set<Id>();
        List<Program_Assignment__c> programAssignmentLst = [SELECT Id, Contact__c 
                                                            FROM Program_Assignment__c
                                                            WHERE(Investigation__c =:parentId OR Service_Case__c =:parentId)
                                                            AND End_Date__c =NULL];
        
        for(Program_Assignment__c paRecord : programAssignmentLst) {
            personIds.add(paRecord.Contact__c);
        }
        
        initWrap.persons = [SELECT Id, Name 
                            FROM Contact 
                            WHERE Id IN:personIds];
        
        
        return JSON.serialize(initWrap);
    }
    
    public class CollateralWrapper {
        
        @AuraEnabled
        Public Collateral__c collateral;
        @AuraEnabled
        Public List<Contact> persons;
        @AuraEnabled
        Public List<Relationship__c> relationshipRecords;
    }
    
    
}