force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>IF( NOT( ISBLANK(  Date_of_Birth__c  ) ) &amp;&amp;   ISBLANK( Date_of_Death__c ) ,
  IF( DATE( 2000 , MONTH( Date_of_Birth__c ) , DAY( Date_of_Birth__c) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
     YEAR (Today()) - YEAR ( Date_of_Birth__c ),
     YEAR (Today()) - YEAR ( Date_of_Birth__c ) -1 ),
  IF(NOT( ISBLANK(  Date_of_Birth__c  ) ) &amp;&amp;   NOT(ISBLANK( Date_of_Death__c )),IF( DATE( 2000 , MONTH( Date_of_Birth__c ) , DAY( Date_of_Birth__c) ) &lt;= DATE( 2000 , MONTH( Date_of_Death__c ) , DAY( Date_of_Death__c ) ),
     YEAR (Date_of_Death__c) - YEAR ( Date_of_Birth__c ),
     YEAR (Date_of_Death__c) - YEAR ( Date_of_Birth__c ) -1 ),null) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Casevault_PID__c.field-meta.xml
<CustomField>
    <fullName>Casevault_PID__c</fullName>
    <label>Casevault PID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/batchAccountUpdate.cls
global class batchAccountUpdate implements Database.Batchable<sObject> {
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
			
        return Database.getQueryLocator([SELECT Id, Casevault_PID__c, Age__c FROM Contact]);
	}
	
	global void execute(Database.BatchableContext BC, List<Contact> scope) {
		    
        for(Contact con : scope) {
            con.Suffix = '('+con.Casevault_PID__c;
            if(con.Age__c !=null) {
                con.Suffix += ', Age-'+con.Age__c;
            }
           con.Suffix +=')';
        }
        Database.update(scope, false);
	}
	
	global void finish(Database.BatchableContext BC) {
	}
}