force-app/main/default/objects/Contact/fields/Child_a_member_in_federal_Tribe__c.field-meta.xml
<CustomField>
    <fullName>Child_a_member_in_federal_Tribe__c</fullName>
    <description>Has the State agency determined if the child is a member 
of or eligible for membership in a federally recognized Tribe.</description>
    <inlineHelpText>Has the State agency determined if the child is a member 
of or eligible for membership in a federally recognized Tribe.</inlineHelpText>
    <label>Child a member in federal Tribe?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <inlineHelpText>It is a standard help text.
But cannot use next line, bold
Character limit around 500 character</inlineHelpText>
    <label>Date of Birth ⓕ</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Hispanic_Latino_Origin__c.field-meta.xml
<CustomField>
    <fullName>Hispanic_Latino_Origin__c</fullName>
    <label>Hispanic/Latino Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black or African American</fullName>
            </value>
            <value>
                <fullName>American Indian or Alaska Native</fullName>
            </value>
            <value>
                <fullName>Asian</fullName>
            </value>
            <value>
                <fullName>Native Hawaiian or Other Pacific Islander</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investigation__c/Investigation__c.object-meta.xml
<CustomObject>
    <label>Investigation</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Investigation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investigations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Investigation__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Connect</label>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipLabel>Investigations</relationshipLabel>
    <relationshipName>Investigations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipName>Persons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <label>Person</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Persons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Person_Role__c.field-meta.xml
<CustomField>
    <fullName>Person_Role__c</fullName>
    <label>Person Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Person_Role</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Person__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipName>Persons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/Program_Assignment__c.object-meta.xml
<CustomObject>
    <label>Program Area</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Program Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Area</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Assignment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Investigation__c.field-meta.xml
<CustomField>
    <fullName>Investigation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Investigation</label>
    <referenceTo>Investigation__c</referenceTo>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Program_Area__c.field-meta.xml
<CustomField>
    <fullName>Program_Area__c</fullName>
    <label>Program Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CPS-IR</fullName>
            </value>
            <value>
                <fullName>CPS-AR</fullName>
            </value>
            <value>
                <fullName>In Home</fullName>
            </value>
            <value>
                <fullName>GAP</fullName>
            </value>
            <value>
                <fullName>Adoption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Program_Sub_Area__c.field-meta.xml
<CustomField>
    <fullName>Program_Sub_Area__c</fullName>
    <label>Program Sub Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Program_Area__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Family Preservation</fullName>
            </value>
            <value>
                <fullName>Interagency Family Preservation Services</fullName>
            </value>
            <value>
                <fullName>Investigation Services Provided</fullName>
            </value>
            <value>
                <fullName>Out of Home - Child</fullName>
            </value>
            <value>
                <fullName>Parent/Guardian of Child in OOH</fullName>
            </value>
            <value>
                <fullName>Sibling of Child in OOH</fullName>
            </value>
            <value>
                <fullName>Child of a Minor Parent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Assignment__c/fields/Service_Case__c.field-meta.xml
<CustomField>
    <fullName>Service_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Case</label>
    <referenceTo>Service_Case__c</referenceTo>
    <relationshipName>Program_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Case__c/Service_Case__c.object-meta.xml
<CustomObject>
    <label>Service Case</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Service Case ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Cases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Person_Role.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Adoptive Parent</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Biological Child</fullName>
    </customValue>
    <customValue>
        <fullName>Adult Child</fullName>
    </customValue>
    <customValue>
        <fullName>Advocate</fullName>
    </customValue>
    <customValue>
        <fullName>Alleged Maltreator</fullName>
    </customValue>
    <customValue>
        <fullName>Alleged Victim</fullName>
    </customValue>
    <customValue>
        <fullName>Biological Child</fullName>
    </customValue>
    <customValue>
        <fullName>Biological Parent</fullName>
    </customValue>
    <customValue>
        <fullName>Caregiver</fullName>
    </customValue>
    <customValue>
        <fullName>CASA Worker</fullName>
    </customValue>
    <customValue>
        <fullName>Child</fullName>
    </customValue>
    <customValue>
        <fullName>Child Attorney</fullName>
    </customValue>
    <customValue>
        <fullName>Child Day Care Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Conservator</fullName>
    </customValue>
    <customValue>
        <fullName>Court Therapist</fullName>
    </customValue>
    <customValue>
        <fullName>CPS Hist. Clrnc.- Requestor</fullName>
    </customValue>
    <customValue>
        <fullName>CPS Hist. Clrnc. - Subject</fullName>
    </customValue>
    <customValue>
        <fullName>Enhanced Aftercare Recipient</fullName>
    </customValue>
    <customValue>
        <fullName>Foster Parent</fullName>
    </customValue>
    <customValue>
        <fullName>Friend/Neighbor</fullName>
    </customValue>
    <customValue>
        <fullName>I &amp; R Participant</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Guardian</fullName>
    </customValue>
    <customValue>
        <fullName>Legal Representive</fullName>
    </customValue>
    <customValue>
        <fullName>Medical Professional</fullName>
    </customValue>
    <customValue>
        <fullName>Mental Health Professional</fullName>
    </customValue>
    <customValue>
        <fullName>Non-Victim Child</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Other Adult</fullName>
    </customValue>
    <customValue>
        <fullName>Other Adult Child</fullName>
    </customValue>
    <customValue>
        <fullName>Other Child</fullName>
    </customValue>
    <customValue>
        <fullName>Private Adoptive Child</fullName>
    </customValue>
    <customValue>
        <fullName>Other Child (Not in Household)</fullName>
        <isActive>false</isActive>
        <label>Other Child (Not in Household)</label>
    </customValue>
    <masterLabel>Person Role</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AFCARSController.cls
public with sharing class AFCARSController {
    
    @AuraEnabled
    Public static String getPersons(String recordId) {
        
        if(!String.isBlank(recordId)) {
        
        Set<Id> personIds = new Set<Id>();
        
        for(Program_Assignment__c assignmentIns : [SELECT Id, Program_Area__c, Contact__c 
                                                   FROM Program_Assignment__c 
                                                   WHERE (Service_Case__c = :recordId OR Investigation__c =:recordId)
                                                   AND Program_Sub_Area__c = 'Out of Home - Child'
                                                   AND Program_Area__c = 'Out of Home'
                                                   ORDER BY Program_Area__c ASC]) 
            {
                if(assignmentIns.Program_Area__c == 'Out of Home') {
                    personIds.add(assignmentIns.Contact__c);
                } 
            }
        
        List<Person__c> persons = [SELECT Id, Person__c, Person__r.Name, Person__r.Date_of_Birth__c, 
                                  Person__r.Gender__c, Person__r.Race__c, Person__r.Hispanic_Latino_Origin__c,
                                  Person__r.Child_a_member_in_federal_Tribe__c
                                  FROM Person__c
                                  WHERE Person__c IN:personIds
                                  AND (Service_Case__c = :recordId OR Investigation__c =:recordId)
                                  AND Person__r.RecordType.Name ='Persons Involved'
                                  AND Person_Role__c INCLUDES ('Biological Child','Other Child (Not in Household)','Private Adoptive Child')];
        
       
        return JSON.serialize(persons);
        } else {
            return NULL;
        }
    }

}